export enum OpenUrlSearchKey {
    SID = 'sid',
    ISSN = 'issn',
    E_ISSN = 'eissn',
    ISBN = 'isbn',
    TITLE = 'title',
    S_TITLE = 'stitle',
    A_TITLE = 'atitle',
    AU_FIRST = 'aufirst',
    AU_LAST = 'aulast',
    VOLUME = 'volume',
    ISSUE = 'issue',
    S_PAGE = 'spage',
    E_PAGE = 'epage',
    PAGES = 'pages',
    ART_NUM = 'artnum',
    DATE = 'date',
    SORT = 'sort',
    LIMIT = 'limit',
    OFFSET = 'offset'
}

export const OpenUrlSearchKeys = [
    OpenUrlSearchKey.SID,
    OpenUrlSearchKey.ISSN,
    OpenUrlSearchKey.E_ISSN,
    OpenUrlSearchKey.ISBN,
    OpenUrlSearchKey.TITLE,
    OpenUrlSearchKey.S_TITLE,
    OpenUrlSearchKey.A_TITLE,
    OpenUrlSearchKey.AU_FIRST,
    OpenUrlSearchKey.AU_LAST,
    OpenUrlSearchKey.VOLUME,
    OpenUrlSearchKey.ISSUE,
    OpenUrlSearchKey.S_PAGE,
    OpenUrlSearchKey.E_PAGE,
    OpenUrlSearchKey.PAGES,
    OpenUrlSearchKey.ART_NUM,
    OpenUrlSearchKey.DATE,
    OpenUrlSearchKey.SORT,
    OpenUrlSearchKey.LIMIT,
    OpenUrlSearchKey.OFFSET
];
