name: Plan and deploy certificate

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}-cert
  cancel-in-progress: true

jobs:
  install-ember:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: "14"
        - run: npm install -g ember-cli
  infrastructure:
    uses: jordanallen-dev/reusable-terraform-workflow/.github/workflows/terraform.yml@main
    with:
      module-path: infra/certificate
      apply-environment: certificate
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
