name: Translation source change Notification with Amazon SES

on:
  push:
    branches:
      - master
      - notify-translation-source-changes
    paths:
      - "pep/translations/en-us.json"

jobs:
  env:
    name: "Setup dynamic environment variables"
    runs-on: ubuntu-latest
    environment: production-vars
    outputs:
      translation_email_sender: ${{ steps.set-outputs.outputs.translation_email_sender}}
      translation_email_recipients: ${{ steps.set-outputs.outputs.translation_email_recipients}}
    steps:
      - name: Set output
        id: set-outputs
        run: |
          echo "translation_email_sender=${{ vars.TRANSLATION_EMAIL_SENDER }}" >> $GITHUB_OUTPUT
          echo "translation_email_recipients=${{ vars.TRANSLATION_EMAIL_RECIPIENTS }}" >> $GITHUB_OUTPUT

  notify-on-change:
    needs: [env]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check for file changes
        id: file-check
        run: |
          echo "FILE_CHANGED=false" > $GITHUB_ENV
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'pep/translations/en-us.json'; then
            echo "FILE_CHANGED=true" > $GITHUB_ENV
          fi

      - name: Setup AWS CLI
        if: env.FILE_CHANGED == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Send notification via Amazon SES
        if: env.FILE_CHANGED == 'true'
        run: |
          FILE_URL="https://github.com/${{ github.repository }}/blob/${{ github.sha }}/pep/translations/en-us.json"
          aws ses send-email \
            --from "${{ needs.env.outputs.translation_email_sender }}" \
            --destination "ToAddresses=${{ needs.env.outputs.translation_email_recipients }}" \
            --message "Subject={Data=Your file was changed,Charset=utf8},Body={Text={Data=The specific file you are monitoring was changed. View the file at: $FILE_URL ,Charset=utf8}}"
